services:
  # Contenedor de la API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080" # Localhost:5000 -> Contenedor:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TuBaseDeDatos;User Id=sa;Password=TuPasswordSeguro123!;TrustServerCertificate=True
    depends_on:
      - db

  # Contenedor de SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_local
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPasswordSeguro123!
    ports:
      - "1450:1433" # Para que puedas entrar desde SSMS
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: